# Generated by Django 5.1.7 on 2025-03-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('url', 'name')},
        ),
    ]
