# Generated by Django 5.1.7 on 2025-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Noutbuk', 'verbose_name_plural': 'Noutbuklar'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Noutbuk nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Sayt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='URL'),
        ),
    ]
